version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: IgorroDB
      POSTGRES_USER: Igor
      POSTGRES_PASSWORD: 12345678
    ports:
      - "8080:8080"
